#!/usr/bin/env python3
"""Builds a host test for the Modbus master's configuration handover.

Same approach as gen_poller_test.py: the functions that matter are cut out of
mb_tcp_master.c verbatim and given stubs, so the test cannot drift from the
code it guards.

What it proves is the property the handover exists for -- that a configuration
change landing in the middle of a poll cannot make one device's reading appear
under another device's name. An outside review reproduced exactly that against
the previous design, where the polling task read the shared configuration
while the HTTP task replaced it with an unsynchronised memcpy.

  make -C test/host master
"""
import pathlib
from cutter import Source

ROOT   = pathlib.Path(__file__).resolve().parents[2]
src    = Source(ROOT / "apps/full/main/mb_tcp_master.c")
budget = Source(ROOT / "apps/full/main/net_budget.h")


HARNESS = r'''
/* GENERATED by gen_master_test.py -- do not edit; edit mb_tcp_master.c. */
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "app_config.h"

#define TAG "mb_master"
#define ESP_LOGD(...)   ((void)0)
#define ESP_LOGW(...)   ((void)0)
#define ESP_LOGI(...)   ((void)0)
#define ESP_LOGE(...)   ((void)0)
__DEFINES__

/* cut from the source: what one attempt returned */
__TYPES__

typedef struct { int fd; } conn_t;
static conn_t   s_conns[CONN_CACHE];
static unsigned conn_closes;
static void conn_close(conn_t *c) { c->fd = -1; conn_closes++; }

static entry_state_t s_state[APP_CFG_MBM_COUNT];
static int64_t  fake_now = 1000;
static int64_t  now_ms(void) { return fake_now; }

/* The mutex is a counter: the test is single-threaded and drives the
   interleaving itself, but a lock left unbalanced still shows up. */
static int lock_depth, lock_max;
#define ST_LOCK()   do { if (++lock_depth > lock_max) lock_max = lock_depth; } while (0)
#define ST_UNLOCK() do { lock_depth--; } while (0)

/* What the HTTP task would have stored. */
static app_config_t fake_cfg;
const app_config_t *app_config_get(void) { return &fake_cfg; }

/* read_value() is cut from the source and tested; what it calls is stubbed.
   The retry decision lives in read_value, and it is the thing an outside
   review found wrong -- a host that cannot be reached at all was dialled
   twice per poll. Counting the calls is how that is pinned down. */
static rd_result_t read_script[4] = { RD_OK, RD_OK, RD_OK, RD_OK };
static unsigned    read_calls;
static double      read_value_out = 123.0;
static char        read_host_seen[APP_CFG_MBM_HOST_LEN + 1];
static char        read_name_seen[APP_CFG_MBM_NAME_LEN + 1];
static void      (*during_read)(void);

static uint16_t mb_value_regs(uint8_t type) { return type <= MBM_VAL_S16 ? 1 : 2; }

static rd_result_t read_once(const mbm_poll_t *e, uint16_t regs, double *value,
                             char *err, size_t err_len)
{
    (void)regs;
    strlcpy(read_host_seen, e->host, sizeof(read_host_seen));
    strlcpy(read_name_seen, e->name, sizeof(read_name_seen));
    if (during_read) { void (*f)(void) = during_read; during_read = NULL; f(); }

    rd_result_t r = read_script[read_calls < 4 ? read_calls : 3];
    read_calls++;
    if (r != RD_OK) { snprintf(err, err_len, "no answer"); return r; }
    /* The real one scales before it returns. */
    *value = read_value_out * (double)e->scale;
    return RD_OK;
}

/* Where a published value ends up. */
static char     pub_topic[64];
static char     pub_payload[32];
static unsigned pub_count;
static int app_mqtt_publish(const char *t, const char *p, int len, int qos, bool ret)
{ (void)qos; (void)ret; strlcpy(pub_topic, t, sizeof(pub_topic));
  snprintf(pub_payload, sizeof(pub_payload), "%.*s", len, p); pub_count++; return 0; }
static void scripting_on_mqtt_message(const char *t, size_t tl, const char *d, size_t dl)
{ (void)t; (void)tl; (void)d; (void)dl; }

/* --- cut from mb_tcp_master.c ------------------------------------------ */
__CUT__
/* ----------------------------------------------------------------------- */

static int failures;
#define CHECK(c, ...) do { if (!(c)) { failures++; printf("  FEHLER: "); \
                                       printf(__VA_ARGS__); printf("\n"); } } while (0)

static void set_entry(int i, const char *name, const char *host, float scale, uint32_t iv)
{
    mbm_poll_t *e = &fake_cfg.mbm[i];
    memset(e, 0, sizeof(*e));
    e->enable = 1; e->unit_id = 1; e->fc = 3; e->type = MBM_VAL_U16;
    e->port = 502; e->scale = scale; e->interval_ms = iv;
    strlcpy(e->name, name, sizeof(e->name));
    strlcpy(e->host, host, sizeof(e->host));
}

/* The HTTP task's half of a save, as web_server.c performs it. */
static void http_saves_new_entry(void)
{
    set_entry(0, "new_meter", "192.0.2.2", 10.0f, 200);
    stage_config();
}

int main(void)
{
    printf("Konfigurationsuebergabe des Modbus-TCP-Masters\n");

    /* 1. A save that lands in the middle of a poll must not reach that poll.
          The previous design read the shared table directly, and a copy
          interrupted between fields published the old host's reading under
          the new name. */
    memset(s_state, 0, sizeof s_state);
    set_entry(0, "old_meter", "192.0.2.1", 1.0f, 86400000);
    stage_config();
    apply_staged_config();
    CHECK(s_active[0].enable && !strcmp(s_active[0].host, "192.0.2.1"),
          "Uebernahme hat die Tabelle nicht geladen");

    during_read = http_saves_new_entry;     /* the save happens mid-poll */
    poll_entry(&s_active[0], &s_state[0]);

    CHECK(!strcmp(read_host_seen, "192.0.2.1"), "gelesen wurde %s", read_host_seen);
    CHECK(!strcmp(read_name_seen, "old_meter"), "gelesen als %s", read_name_seen);
    CHECK(!strcmp(pub_topic, "modbus/old_meter"),
          "veroeffentlicht unter %s", pub_topic);
    CHECK(!strcmp(pub_payload, "123"), "veroeffentlicht als %s", pub_payload);
    printf("  Speichern waehrend des Polls: gelesen und veroeffentlicht als %s\n",
           pub_topic);

    /* 2. The new table takes effect at the next handover, and everything the
          old entry left behind goes with it. */
    conn_closes = 0;
    for (int i = 0; i < CONN_CACHE; i++) s_conns[i].fd = 5;   /* as if open */
    fake_now = 5000;
    apply_staged_config();
    CHECK(!strcmp(s_active[0].name, "new_meter"), "neue Tabelle nicht uebernommen");
    CHECK(!strcmp(s_active[0].host, "192.0.2.2"), "neuer Host nicht uebernommen");
    CHECK(!s_state[0].value_ms && s_state[0].value == 0 && s_state[0].reads == 0,
          "alter Status nicht geloescht");
    CHECK(s_state[0].due_ms == 5000, "Termin nicht auf jetzt gesetzt (%lld)",
          (long long)s_state[0].due_ms);
    /* Faechern, nicht alle auf denselben Augenblick: eine Tabelle voller
       abgeschalteter Hosts wuerde sonst eine Verbindungsfrist nach der
       anderen zahlen, bevor ein gesunder Eintrag ueberhaupt drankommt. */
    for (int i = 1; i < APP_CFG_MBM_COUNT; i++)
        CHECK(s_state[i].due_ms > s_state[i - 1].due_ms,
              "Termin %d nicht gegen %d versetzt (%lld vs %lld)", i, i - 1,
              (long long)s_state[i].due_ms, (long long)s_state[i - 1].due_ms);
    CHECK(conn_closes == CONN_CACHE, "Verbindungen nicht verworfen");
    printf("  Uebernahme danach: Status geleert, Termine gefaechert, Verbindungen verworfen\n");

    /* 3. The new entry is polled with the new scale, under the new name. */
    pub_count = 0;
    poll_entry(&s_active[0], &s_state[0]);
    CHECK(!strcmp(read_host_seen, "192.0.2.2"), "gelesen wurde %s", read_host_seen);
    CHECK(!strcmp(pub_topic, "modbus/new_meter"), "veroeffentlicht unter %s", pub_topic);
    CHECK(!strcmp(pub_payload, "1230"), "Skalierung nicht angewandt: %s", pub_payload);
    printf("  neuer Eintrag: %s = %s\n", pub_topic, pub_payload);

    /* 4. A handover with nothing staged changes nothing. */
    int64_t before = s_state[0].due_ms;
    double  val    = s_state[0].value;
    apply_staged_config();
    CHECK(s_state[0].due_ms == before && s_state[0].value == val,
          "Uebernahme ohne Anforderung hat etwas veraendert");
    printf("  Uebernahme ohne Anforderung aendert nichts\n");

    /* 5. A failed read leaves no value and arms the backoff. */
    read_script[0] = RD_FAILED;
    read_calls = 0;
    poll_entry(&s_active[0], &s_state[0]);
    CHECK(s_state[0].errors == 1, "Fehler nicht gezaehlt");
    CHECK(s_state[0].backoff_ms == BACKOFF_FIRST_MS, "Backoff nicht gesetzt");
    CHECK(s_state[0].value_ms != 0, "ein frueherer gueltiger Wert wurde verworfen");
    CHECK(read_calls == 1, "nicht wiederholbarer Fehler wurde wiederholt (%u)", read_calls);
    read_script[0] = RD_OK;
    printf("  fehlgeschlagener Poll: Backoff gesetzt, letzter Wert bleibt, kein zweiter Versuch\n");

    /* 6. The retry decision. Only a connection kept from an earlier poll is
          worth a second attempt; a host that cannot be reached at all, or a
          device that answered, must not be asked twice -- that cost two full
          connect timeouts per poll on the one polling task. */
    char err[48]; double v = 0;

    read_calls = 0; read_script[0] = RD_OK;
    CHECK(read_value(&s_active[0], &v, err, sizeof err) && read_calls == 1,
          "Erfolg brauchte %u Versuche", read_calls);

    read_calls = 0; read_script[0] = RD_FAILED;
    CHECK(!read_value(&s_active[0], &v, err, sizeof err) && read_calls == 1,
          "endgueltiger Fehler wurde wiederholt (%u Versuche)", read_calls);

    read_calls = 0; read_script[0] = RD_STALE_CONN; read_script[1] = RD_OK;
    CHECK(read_value(&s_active[0], &v, err, sizeof err) && read_calls == 2,
          "veraltete Verbindung: %u Versuche, erwartet 2", read_calls);

    read_calls = 0; read_script[0] = RD_STALE_CONN; read_script[1] = RD_FAILED;
    CHECK(!read_value(&s_active[0], &v, err, sizeof err) && read_calls == 2,
          "veraltete Verbindung mit zweitem Fehlschlag: %u Versuche", read_calls);

    read_calls = 0; read_script[0] = RD_STALE_CONN; read_script[1] = RD_STALE_CONN;
    CHECK(!read_value(&s_active[0], &v, err, sizeof err) && read_calls == 2,
          "mehr als ein zweiter Versuch (%u)", read_calls);
    read_script[1] = RD_OK;
    printf("  Wiederholung nur bei veralteter Verbindung, und nur einmal\n");

    CHECK(lock_depth == 0, "Sperre nicht ausgeglichen (%d)", lock_depth);
    CHECK(lock_max == 1, "Sperre wurde verschachtelt genommen (%d)", lock_max);

    printf("%s\n", failures ? "FEHLER" : "alles in Ordnung");
    return failures ? 1 : 0;
}
'''

cuts = "".join(src.func(sig) for sig in (
    "static bool read_value(const mbm_poll_t *e, double *value, char *err, size_t err_len)",
    "static void publish(const mbm_poll_t *e, double value)",
    "static void poll_entry(const mbm_poll_t *e, entry_state_t *st)",
    "static void apply_staged_config(void)",
    "static void stage_config(void)",
))
# s_active / s_staged / s_reload_pending are declared next to the comment that
# explains them; take them with their explanation.
decl = src.span("static mbm_poll_t    s_active", "static volatile bool s_reload_pending;")

out = pathlib.Path(__file__).with_name("test_mb_master.c")
defines = (budget.defines("NET_SOCK_MB_MASTER") +
           src.defines("CONN_CACHE", "BACKOFF_FIRST_MS", "BACKOFF_MAX_MS"))
out.write_text(HARNESS.replace("__DEFINES__", defines)
                      .replace("__TYPES__", src.type("} rd_result_t;") +
                                       src.type("} entry_state_t;"))
                      .replace("__CUT__", decl + "\n\n" + cuts))
print("erzeugt:", out.name)
