#!/usr/bin/env python3
"""Builds a host test for the TCP server's receive path out of the real source.

The receive path cannot be compiled on a development machine as it stands --
it reaches FreeRTOS, lwIP and the logging layer. So the functions that matter
are cut out of mb_tcp_server.c verbatim and given stubs for the rest. Cutting
rather than copying is the point: the test cannot drift away from the code it
is meant to guard. The same argument applies to the #defines and to the types
the cut functions work on, so those are cut as well -- a field added to conn_t
or a number changed in net_budget.h arrives here without anyone editing this
file.

Checks two things the previous design got wrong, both demonstrated against it
by an outside review:

  - a client that sends one byte and stops must delay nobody else
  - a frame has one deadline covering all of it, not one per read, so a client
    cannot extend it by arriving in pieces

and the three ways a request leaves pump_slot(): answered on the poller,
handed to a worker, or refused with "slave device busy" when the pool is full.

Run through the Makefile: make -C test/host poller
"""
import pathlib
from cutter import Source

ROOT   = pathlib.Path(__file__).resolve().parents[2]
src    = Source(ROOT / "apps/full/main/mb_tcp_server.c")
budget = Source(ROOT / "apps/full/main/net_budget.h")


HARNESS = r'''
/* GENERATED by gen_poller_test.py -- do not edit; edit mb_tcp_server.c. */
#include <assert.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "mb_pdu.h"

#define pdTRUE              1
#define MSG_DONTWAIT     0x08
__DEFINES__
#define ESP_LOGW(...)    ((void)0)

/* --- cut from mb_tcp_server.c: the types the functions below work on ----- */
__TYPES__
/* ------------------------------------------------------------------------ */

static conn_t s_conn[MB_TCP_MAX_CONN];
static struct { unsigned malformed, overloaded; } s_stats;
/* NULL stands for "no gateway running, so no worker pool" -- the firmware's
   shipping default, and a live branch in pump_slot(). The forwarding tests
   point it at a dummy. */
static void *s_jobs;
static uint8_t s_local_uid = 247;

/* --- the world the cut-out functions see ------------------------------- */

static int64_t  clock_us;
static unsigned answers, closes;
/* Per fd: how much of its script it has delivered, and when the next piece
   becomes available. A negative time means "never". */
static unsigned pos[MB_TCP_MAX_CONN];
static int64_t  ready_at[MB_TCP_MAX_CONN];
static unsigned give[MB_TCP_MAX_CONN];     /* bytes this fd will ever give */

static uint8_t FRAME[] = { 0,1, 0,0, 0,6, 247, 1, 0,0, 0,1 };  /* FC01, local */

/* How a connection behaves once it has given everything it is going to:
   nothing more for now, a clean close, or a reset. The last two are the two
   branches of pump_slot() that close a slot, and without them a regression
   that leaked a slot on a half-close would pass unnoticed. */
enum { END_SILENT = 0, END_EOF, END_RESET };
static int end_mode[MB_TCP_MAX_CONN];

static int64_t esp_timer_get_time(void) { return clock_us; }

/* Non-blocking by contract: it never advances the clock. A test that ends
   with a large clock value therefore means the code under test waited. */
static int recv(int fd, void *buf, size_t n, int flags)
{
    (void)flags;
    if (clock_us < ready_at[fd]) { errno = EAGAIN; return -1; }
    if (pos[fd] >= give[fd]) {
        if (end_mode[fd] == END_EOF)   return 0;
        if (end_mode[fd] == END_RESET) { errno = ECONNRESET; return -1; }
        errno = EAGAIN; return -1;
    }
    size_t avail = give[fd] - pos[fd];
    if (n > avail) n = avail;
    memcpy(buf, FRAME + pos[fd], n);
    pos[fd] += n;
    return (int)n;
}

static int  close(int fd)                                   { (void)fd; closes++; return 0; }
static uint16_t process(const uint8_t *f, uint16_t n, uint8_t *o)
{ (void)f; assert(n == sizeof FRAME); answers++; memset(o, 0xA5, 9); return 9; }
/* Per fd: how many bytes its receive window will still take, and what went
   out of it. A send is non-blocking by contract and never advances the clock,
   so a test that ends with time on it means the code under test waited. The
   bytes are kept because what build_busy() puts on the wire is a Modbus
   exception response, and only the bytes say whether it is the right one. */
static int      window[MB_TCP_MAX_CONN];
static unsigned sent_bytes[MB_TCP_MAX_CONN];
static uint8_t  sent_buf[MB_TCP_MAX_CONN][FRAME_MAX];

static int send(int fd, const void *buf, size_t n, int flags)
{
    (void)flags;
    if (window[fd] <= 0) { errno = EAGAIN; return -1; }
    if ((int)n > window[fd]) n = (size_t)window[fd];
    if (sent_bytes[fd] + n <= sizeof sent_buf[fd])
        memcpy(sent_buf[fd] + sent_bytes[fd], buf, n);
    window[fd] -= (int)n;
    sent_bytes[fd] += (unsigned)n;
    return (int)n;
}

/* The pool, as far as pump_slot() can tell. queue_ok says whether a worker
   was free; queued_slot/queued_len are what it was asked to do. */
static bool     queue_ok;
static int      queued_slot;
static uint16_t queued_len;
static unsigned queued;

static int xQueueSend(void *q, const void *j, int t)
{
    (void)q; (void)t;
    if (!queue_ok) return 0;
    const job_t *job = (const job_t *)j;
    queued_slot = job->slot;
    queued_len  = job->len;
    queued++;
    return pdTRUE;
}

/* --- cut from mb_tcp_server.c ------------------------------------------ */
__CUT__
/* ----------------------------------------------------------------------- */

static int failures;
#define CHECK(c, ...) do { if (!(c)) { failures++; printf("  FEHLER: "); \
                                       printf(__VA_ARGS__); printf("\n"); } } while (0)

static int dummy_queue;                 /* a non-NULL s_jobs to point at */

static void reset(void)
{
    memset(s_conn, 0, sizeof s_conn);
    memset(pos, 0, sizeof pos);
    memset(give, 0, sizeof give);
    memset(end_mode, 0, sizeof end_mode);
    memset(ready_at, 0, sizeof ready_at);
    memset(sent_bytes, 0, sizeof sent_bytes);
    memset(sent_buf, 0, sizeof sent_buf);
    clock_us = 0; answers = 0; closes = 0;
    s_stats.malformed = 0; s_stats.overloaded = 0;
    s_jobs = NULL; queue_ok = false; queued = 0;
    queued_slot = -1; queued_len = 0;
    for (int i = 0; i < MB_TCP_MAX_CONN; i++) {
        s_conn[i].fd = i; s_conn[i].state = SLOT_IDLE;
        window[i] = 1 << 20;                    /* takes everything by default */
    }
}

int main(void)
{
    printf("Empfangspfad des TCP-Servers\n");

    /* 1. Seven clients send one byte and stop; the eighth sends a whole
          request. The eighth must be answered on this pass, and the poll
          loop must not have waited for anybody. */
    reset();
    for (int i = 0; i < 7; i++) give[i] = 1;
    give[7] = sizeof FRAME;
    for (int i = 0; i < MB_TCP_MAX_CONN; i++) pump_slot(i);
    CHECK(answers == 1, "vollstaendige Anfrage nicht beantwortet (%u)", answers);
    CHECK(clock_us == 0, "der Poller hat gewartet: %lld ms", (long long)(clock_us / 1000));
    CHECK(closes == 0, "eine Verbindung wurde zu frueh geschlossen");
    printf("  sieben stockende Clients, achter beantwortet, Wartezeit %lld ms\n",
           (long long)(clock_us / 1000));

    /* 2. One frame, arriving in pieces either side of the deadline. The
          header completes at 180 ms, the body would complete at 360 -- one
          deadline of 200 ms from the first byte must end it first. */
    reset();
    give[0] = 1; ready_at[0] = 0;
    pump_slot(0);                           /* first byte at t = 0 */
    CHECK(s_conn[0].want == MBAP_HDR, "nach dem ersten Byte wird kein Kopf erwartet");

    clock_us = 180000; give[0] = MBAP_HDR;  /* rest of the header at 180 ms */
    pump_slot(0);
    CHECK(answers == 0, "unvollstaendiger Rahmen beantwortet");

    clock_us = 210000;                      /* past the deadline */
    sweep_deadlines();
    CHECK(s_conn[0].state == SLOT_FREE, "Verbindung nach Fristablauf nicht geschlossen");
    CHECK(s_stats.malformed == 1, "Fristablauf nicht gezaehlt");

    printf("  zerstueckelter Rahmen bei 200 ms beendet, nicht bei 360\n");

    /* 3. A frame that arrives in pieces but inside the deadline is served. */
    reset();
    give[0] = 1;
    pump_slot(0);
    clock_us = 100000; give[0] = sizeof FRAME;
    pump_slot(0);
    CHECK(answers == 1, "rechtzeitiger zerstueckelter Rahmen nicht beantwortet");
    CHECK(s_conn[0].want == 0, "Empfangszustand nicht zurueckgesetzt");
    printf("  zerstueckelter Rahmen innerhalb der Frist beantwortet\n");

    /* 4. A client that has finished a request and then sits idle -- which
          Modbus clients do for hours -- must not be timed out. The deadline
          belongs to a frame in progress, not to the connection. */
    reset();
    give[0] = sizeof FRAME;
    pump_slot(0);
    CHECK(answers == 1, "Anfrage nicht beantwortet");
    clock_us = 3600LL * 1000000;            /* an hour later */
    sweep_deadlines();
    CHECK(s_conn[0].state == SLOT_IDLE, "ruhende Verbindung wurde geschlossen");
    CHECK(closes == 0, "ruhende Verbindung wurde geschlossen");
    printf("  ruhende Verbindung nach einer Stunde noch offen\n");

    /* 5. A header that is not Modbus ends the connection at once -- this is
          what stops a non-Modbus client from holding a slot. */
    reset();
    give[0] = sizeof FRAME;
    FRAME[2] = 1;                           /* protocol id 1 instead of 0 */
    pump_slot(0);
    FRAME[2] = 0;
    CHECK(answers == 0, "Rahmen mit falscher Protokoll-ID wurde beantwortet");
    CHECK(s_conn[0].state == SLOT_FREE, "Verbindung nicht geschlossen");
    CHECK(s_stats.malformed == 1, "nicht als fehlerhaft gezaehlt");

    /* And a length field outside what a PDU can be. */
    reset();
    give[0] = sizeof FRAME;
    FRAME[5] = 1;                           /* length 1: less than the unit id */
    pump_slot(0);
    FRAME[5] = 6;
    CHECK(s_conn[0].state == SLOT_FREE, "Rahmen mit unmoeglicher Laenge angenommen");
    CHECK(s_stats.malformed == 1, "nicht als fehlerhaft gezaehlt");
    printf("  falsche Protokoll-ID und unmoegliche Laenge beenden die Verbindung\n");

    /* 5b. The two ways a peer can go away, both of which must free the slot. */
    reset();
    end_mode[0] = END_EOF;                  /* clean close, nothing given */
    pump_slot(0);
    CHECK(s_conn[0].state == SLOT_FREE, "sauberer Abbruch gibt den Platz nicht frei");
    CHECK(closes == 1, "Socket nicht geschlossen");

    reset();
    end_mode[0] = END_RESET;                /* reset */
    pump_slot(0);
    CHECK(s_conn[0].state == SLOT_FREE, "Reset gibt den Platz nicht frei");
    CHECK(closes == 1, "Socket nicht geschlossen");

    /* A peer that closes mid-frame must not leave the frame half-held. */
    reset();
    give[0] = 3; end_mode[0] = END_EOF;
    pump_slot(0);
    CHECK(s_conn[0].state == SLOT_FREE, "Abbruch mitten im Rahmen nicht behandelt");
    printf("  Abbruch und Reset geben den Platz frei, auch mitten im Rahmen\n");

    /* 6. A client that has stopped reading must not hold the poll loop, and
          must not let another connection's frame deadline slip past unseen.
          Both were demonstrated against the previous version: the next client
          was served at 550 ms and a frame 160 ms over its deadline was still
          executed. */
    reset();
    window[0] = 0;                        /* slot 0 takes nothing at all */
    give[0] = sizeof FRAME;
    pump_slot(0);                         /* answers, cannot send it */
    CHECK(clock_us == 0, "der Poller hat auf den Sendepuffer gewartet: %lld ms",
          (long long)(clock_us / 1000));
    CHECK(s_conn[0].out_len != 0, "die unversandte Antwort wurde nicht gepuffert");
    CHECK(s_conn[0].state == SLOT_IDLE, "Verbindung zu frueh geschlossen");

    give[1] = 1;                          /* slot 1 begins a frame at t = 0 */
    pump_slot(1);
    CHECK(s_conn[1].got == 1, "erstes Byte von Slot 1 nicht angenommen");

    clock_us = 360000;                    /* later than slot 1's deadline */
    give[1] = sizeof FRAME;               /* the rest arrives too late */
    unsigned before = answers;
    pump_slot(1);
    CHECK(answers == before, "verspaeteter Rahmen wurde doch ausgefuehrt");
    CHECK(s_conn[1].state == SLOT_FREE, "verspaetete Verbindung nicht geschlossen");
    printf("  blockierter Sender haelt niemanden auf, verspaeteter Rahmen abgewiesen\n");

    /* 7. The blocked connection itself is dropped once its own deadline has
          passed -- it is holding a buffer nobody is taking. */
    clock_us = 600000;
    sweep_deadlines();
    CHECK(s_conn[0].state == SLOT_FREE, "blockierte Verbindung nicht geschlossen");
    printf("  blockierte Verbindung nach %d ms beendet\n", SEND_WAIT_MS);

    /* 8. A partially accepted answer finishes when the window opens, and the
          connection is then usable again. */
    reset();
    window[0] = 4;                        /* takes four of the nine bytes */
    give[0] = sizeof FRAME;
    pump_slot(0);
    CHECK(s_conn[0].out_len && s_conn[0].out_sent == 4, "Teilversand nicht vermerkt");
    window[0] = 1 << 20;
    CHECK(flush_out(0), "Rest konnte nicht gesendet werden");
    CHECK(s_conn[0].out_len == 0, "Ausgabe nicht als erledigt vermerkt");
    CHECK(sent_bytes[0] == 9, "nicht alle Bytes gesendet (%u)", sent_bytes[0]);
    printf("  Teilversand wird fortgesetzt, sobald das Fenster aufgeht\n");

    /* 9. No gateway, so no worker pool: s_jobs is NULL. A request for a
          foreign unit id has nowhere to be forwarded to and must still be
          answered on the poller rather than left waiting. This is what the
          board ships as, so it is the ordinary case, not a corner. */
    reset();
    FRAME[6] = 5;                         /* not 247, not 0, not 255 */
    give[0] = sizeof FRAME;
    pump_slot(0);
    FRAME[6] = 247;
    CHECK(s_jobs == NULL, "die Vorbedingung stimmt nicht: s_jobs ist belegt");
    CHECK(answers == 1, "fremde Unit-ID ohne Gateway nicht beantwortet (%u)", answers);
    CHECK(queued == 0, "ohne Arbeiterpool wurde eingereiht");
    CHECK(s_conn[0].state == SLOT_IDLE, "Platz nicht wieder freigegeben");
    CHECK(sent_bytes[0] == 9, "Antwort nicht gesendet (%u)", sent_bytes[0]);
    printf("  ohne Gateway wird auch eine fremde Unit-ID am Poller beantwortet\n");

    /* 10. With a pool and a free worker the frame is handed over: the slot
           stays busy, the poller sends nothing, and what was queued names
           this slot and the whole frame. */
    reset();
    s_jobs = &dummy_queue; queue_ok = true;
    FRAME[6] = 5;
    give[0] = sizeof FRAME;
    pump_slot(0);
    FRAME[6] = 247;
    CHECK(queued == 1, "fremde Unit-ID nicht an den Pool uebergeben (%u)", queued);
    CHECK(queued_slot == 0 && queued_len == (uint16_t)sizeof FRAME,
          "falscher Auftrag eingereiht: Platz %d, Laenge %u",
          queued_slot, (unsigned)queued_len);
    CHECK(s_conn[0].state == SLOT_BUSY, "Platz nicht als belegt vermerkt");
    CHECK(answers == 0, "der Poller hat selbst geantwortet");
    CHECK(sent_bytes[0] == 0, "der Poller hat gesendet (%u Bytes)", sent_bytes[0]);
    CHECK(s_conn[0].out_len == 0, "der Poller hat eine Antwort gepuffert");
    printf("  fremde Unit-ID geht an den Pool, der Platz bleibt belegt\n");

    /* 11. Pool full: the client is told to retry instead of waiting for a
           slot. The bytes have to be a Modbus exception response -- function
           code with the high bit set, exception 0x06 -- or the client sees
           nine bytes of nonsense and gives up. */
    reset();
    s_jobs = &dummy_queue; queue_ok = false;
    FRAME[6] = 5;
    give[0] = sizeof FRAME;
    pump_slot(0);
    FRAME[6] = 247;
    CHECK(s_stats.overloaded == 1, "Ueberlast nicht gezaehlt (%u)", s_stats.overloaded);
    CHECK(s_conn[0].state == SLOT_IDLE, "Platz nach abgewiesenem Auftrag nicht frei");
    CHECK(answers == 0, "die Anfrage wurde doch ausgefuehrt");
    CHECK(sent_bytes[0] == MB_MBAP_LEN + 2, "falsche Antwortlaenge (%u)", sent_bytes[0]);
    CHECK(sent_buf[0][0] == 0 && sent_buf[0][1] == 1, "Transaktions-ID nicht gespiegelt");
    CHECK(sent_buf[0][2] == 0 && sent_buf[0][3] == 0, "Protokoll-ID nicht 0");
    CHECK(sent_buf[0][4] == 0 && sent_buf[0][5] == 3, "Laengenfeld nicht 3");
    CHECK(sent_buf[0][6] == 5, "Unit-ID nicht gespiegelt (%u)", (unsigned)sent_buf[0][6]);
    CHECK(sent_buf[0][7] == 0x81, "kein Ausnahme-Funktionscode (0x%02X)",
          (unsigned)sent_buf[0][7]);
    CHECK(sent_buf[0][8] == MB_EXC_DEVICE_BUSY, "nicht Ausnahme 0x06 (0x%02X)",
          (unsigned)sent_buf[0][8]);
    printf("  voller Pool antwortet mit Ausnahme 0x%02X statt zu warten\n",
           (unsigned)sent_buf[0][8]);

    printf("%s\n", failures ? "FEHLER" : "alles in Ordnung");
    return failures ? 1 : 0;
}
'''

types = "".join(src.type(e) for e in (
    "SLOT_BUSY };",
    "} conn_t;",
    "} job_t;",
))
cuts = "".join(src.func(sig) for sig in (          # C declaration order
    "static void arm_out(int i, uint16_t len)",
    "static bool is_local(uint8_t uid)",
    "static bool flush_out(int i)",
    "static void close_slot(int i)",
    "static void send_now(int i, uint16_t len)",
    "static bool frame_expired(int i, int64_t now)",
    "static uint16_t build_busy(const uint8_t *frame, uint8_t *out)",
    "static void pump_slot(int i)",
    "static void sweep_deadlines(void)",
))
defines = (budget.defines("NET_SOCK_MB_CONN") +
           src.defines("MBAP_HDR", "FRAME_MAX", "MB_TCP_MAX_CONN",
                       "FRAME_WAIT_MS", "SEND_WAIT_MS"))
out = pathlib.Path(__file__).with_name("test_mb_poller.c")
out.write_text(HARNESS.replace("__DEFINES__", defines)
                      .replace("__TYPES__", types)
                      .replace("__CUT__", cuts))
print("erzeugt:", out.name)
